spring.application.name=RoomManager

# server.port=9090

spring.base=http://localhost:9090


# spring.application.name=HospitalManagement
server.port=9097

# Backend API URL
spring.backend.url=http://localhost:9090
